### ISSUE TITLE
Confusion with hosting

### ISSUE THREAD

**Issue by DanilKorotenko** [jhvanderschee/jekyllcodex#10]
I have a suggestion that this site is hosted not on GitHub pages. Isn't it?
But credits say that it hosted on GitHub pages.

**Comment by jhvanderschee** [comment]
Until 1 day ago it was hosted on Github Pages. I recently changed that because of simplified form handling on CloudCannon and because Fromspree changed their free teir. I also updated the footer accordingly. Note that using Netlify's free teir would work just as well for this purpose. What made you think that it was not hosted on Github? If you want to be sure where a website is hosted you should request its A record. You will see that it currently points to CloudCannon.
